services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://127.0.0.1:8000
    depends_on:
      - web-api
    networks:
      - volatiliweb-net

  web-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - evidence-data:/evidence
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - volatiliweb-net
    command: >
      sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - evidence-data:/evidence:ro
      - symbols-data:/symbols
      - postgres-data:/var/lib/postgresql/data
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - volatiliweb-net
    command: celery -A app.celery_app worker --loglevel=info --concurrency=2

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - volatiliweb-net

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - volatiliweb-net


volumes:
  postgres-data:
    name: volatiliweb_postgres-data-fix
  evidence-data:
    name: volatiliweb_evidence-data
  symbols-data:
    name: volatiliweb_symbols-data

networks:
  volatiliweb-net:
    driver: bridge
